// lyrike-studio/features/media/ui/SourcePanel.tsx
"use client";

import { PublishCard } from "@/features/publish";

import { useEditorUIStore } from "@/features/editor/store/editorUIStore";
import { useEditorMediaStore } from "@/features/editor/store/editorMediaStore";
import { useLyricsStore } from "@/entities/lyrics/store/lyricsStore";
import {
  useLoadMedia,
  useTranscribeMutation,
  usePublishMutation,
} from "@/features/media/queries";
import { useCallback, useMemo } from "react";
import { formatTime } from "@/shared/utils/formatters";
import Image from "next/image";

export function SourcePanel() {
  const activeTab = useEditorUIStore((s) => s.activeTab);

  const sourceInput = useEditorMediaStore((s) => s.sourceInput);
  const setSourceInput = useEditorMediaStore((s) => s.setSourceInput);
  const sourceMessage = useEditorMediaStore((s) => s.sourceMessage);
  const setSourceMessage = useEditorMediaStore((s) => s.setSourceMessage);
  const mediaInfo = useEditorMediaStore((s) => s.mediaInfo);
  const setMediaInfo = useEditorMediaStore((s) => s.setMediaInfo);
  const setPeaksInfo = useEditorMediaStore((s) => s.setPeaksInfo);
  const fetchState = useEditorMediaStore((s) => s.fetchState);
  const setFetchState = useEditorMediaStore((s) => s.setFetchState);
  const transcribeState = useEditorMediaStore((s) => s.transcribeState);
  const setTranscribeState = useEditorMediaStore((s) => s.setTranscribeState);
  const setPeaksState = useEditorMediaStore((s) => s.setPeaksState);
  const setPeaksMessage = useEditorMediaStore((s) => s.setPeaksMessage);

  const hydrateFromMedia = useLyricsStore((s) => s.hydrateFromMedia);
  const importFromLrc = useLyricsStore((s) => s.importFromLrc);
  const exportToLrc = useLyricsStore((s) => s.exportToLrc);
  const doc = useLyricsStore((s) => s.doc);
  const selectedLineId = useLyricsStore((s) => s.selectedLineId);
  const activeLineId = useLyricsStore((s) => s.activeLineId);
  const tab = useLyricsStore((s) => s.tab);
  const isAutoSyncEnabled = useLyricsStore((s) => s.isAutoSyncEnabled);

  const lyricsState = useMemo(
    () => ({
      doc,
      selectedLineId,
      activeLineId,
      tab,
      isAutoSyncEnabled,
      canUndo: false,
      canRedo: false,
    }),
    [doc, selectedLineId, activeLineId, tab, isAutoSyncEnabled],
  );

  const loadMediaMutation = useLoadMedia({
    onSuccess: (info) => {
      hydrateFromMedia({
        duration: info.duration,
        title: info.trackName,
        artist: info.artistName,
      });
    },
    onError: (error) => {
      setSourceMessage(error.message);
    },
  });

  const transcribeMutation = useTranscribeMutation({
    onSuccess: (lrc) => {
      importFromLrc(lrc);
      setSourceMessage("Transcription completed.");
    },
    onError: (error) => {
      setSourceMessage(`Transcription failed: ${error.message}`);
    },
    onStatusChange: (status) => {
      if (status === "starting" || status === "running") {
        setSourceMessage(`Transcribing... ${status}`);
      }
    },
  });

  const publishMutation = usePublishMutation({
    onSuccess: () => {
      setSourceMessage("Lyrics published successfully!");
    },
    onError: (error) => {
      setSourceMessage(`Publish failed: ${error.message}`);
    },
  });

  const onFetch = useCallback(async () => {
    if (!sourceInput.trim()) {
      setSourceMessage("Please enter a valid source URL.");
      setFetchState("error");
      return;
    }
    setSourceMessage("Fetching metadata and caching audio...");
    setFetchState("loading");
    try {
      const data = await loadMediaMutation.mutateAsync(sourceInput);
      setMediaInfo(data.mediaInfo);
      setPeaksInfo(data.peaksInfo);
      setPeaksState(data.peaksState);
      setPeaksMessage(data.peaksMessage);
      setFetchState("ready");
    } catch (e) {
      setFetchState("error");
    }
  }, [
    sourceInput,
    loadMediaMutation,
    setSourceMessage,
    setFetchState,
    setMediaInfo,
    setPeaksInfo,
    setPeaksState,
    setPeaksMessage,
  ]);

  const onTranscribe = useCallback(async () => {
    if (!mediaInfo) {
      setSourceMessage("Load media before transcribing.");
      return;
    }
    setTranscribeState("loading");
    try {
      await transcribeMutation.transcribeAsync(mediaInfo.videoId);
      setTranscribeState("ready");
    } catch (e) {
      setTranscribeState("error");
    }
  }, [mediaInfo, transcribeMutation, setSourceMessage, setTranscribeState]);

  const onPublish = useCallback(async () => {
    if (!mediaInfo) {
      setSourceMessage("Load media before publishing.");
      return;
    }
    await publishMutation.publishAsync({
      lyricsState,
      mediaInfo,
      exportToLrc,
    });
  }, [lyricsState, mediaInfo, publishMutation, exportToLrc, setSourceMessage]);

  return (
    <article
      className={`min-h-0 h-full flex flex-col overflow-x-hidden overflow-y-auto bg-transparent ${activeTab !== "source" ? "hidden md:flex" : ""}`}
    >
      <section className="p-4 flex flex-col gap-3.5 border-b border-line-soft">
        <div className="flex flex-col gap-2">
          <span className="text-[0.7rem] font-bold text-ink-light-soft uppercase tracking-widest">
            Source URL
          </span>
          <div className="relative">
            <input
              type="url"
              value={sourceInput}
              onChange={(e) => setSourceInput(e.target.value)}
              placeholder="Paste YouTube link here..."
              className={`w-full px-4 py-3 rounded-xl border bg-bg-input text-ink text-sm outline-none transition-colors ${
                fetchState === "error"
                  ? "border-danger"
                  : "border-line focus:border-primary-deep focus:ring-4 focus:ring-primary-10"
              }`}
            />
          </div>
        </div>

        <div className="grid grid-cols-1 gap-2">
          <button
            type="button"
            className="px-6 py-2.5 rounded-xl text-sm font-semibold transition-all duration-200 hover:-translate-y-0.5 active:translate-y-0 min-h-[42px] inline-flex items-center justify-center gap-2 tracking-tight bg-accent text-white border-none shadow-sm hover:bg-accent-deep"
            disabled={fetchState === "loading"}
            onClick={onFetch}
          >
            {fetchState === "loading" ? (
              <>
                <span className="w-3.5 h-3.5 border-2 border-white/30 border-t-white rounded-full animate-spin" />{" "}
                Fetching...
              </>
            ) : (
              "Fetch Media"
            )}
          </button>

          <button
            type="button"
            className="min-h-[42px] rounded-xl border border-accent/25 px-5 py-3 inline-flex items-center justify-center gap-2 text-sm font-semibold text-accent transition-all duration-150 cursor-pointer tracking-tight bg-bg-elev hover:bg-bg-soft hover:border-accent/40"
            disabled={
              !mediaInfo ||
              ["starting", "running", "queued"].includes(transcribeState)
            }
            onClick={onTranscribe}
          >
            {["starting", "running", "queued"].includes(transcribeState) ? (
              <>
                <span className="w-2 h-2 bg-accent rounded-full animate-pulse shadow-accent/20 shadow-lg" />{" "}
                Working...
              </>
            ) : (
              "Transcribe"
            )}
          </button>
        </div>

        <div
          className={`border-l-4 border-line rounded-lg p-4 text-sm text-ink-light ${fetchState === "ready" ? "border-l-primary bg-primary-8 text-ink-light" : ""} ${fetchState === "error" ? "border-l-danger bg-danger-8 text-[#fca5a5]" : ""}`}
        >
          <p className="m-0">{sourceMessage}</p>
        </div>
      </section>

      {mediaInfo && (
        <>
          <section className="p-4 flex flex-col gap-3.5 border-b border-line-soft">
            <div className="flex items-center">
              <span className="inline-flex rounded-md bg-primary-10 text-primary px-2 py-1 text-[0.65rem] font-bold uppercase tracking-wider border border-primary-20">
                Metadata
              </span>
            </div>
            <div className="flex flex-col gap-3">
              <div className="flex gap-4 items-start">
                <Image
                  width={112}
                  height={112}
                  src={`https://i.ytimg.com/vi/${mediaInfo.videoId}/mqdefault.jpg`}
                  className="w-28 aspect-square rounded-xl object-cover shadow-sm bg-bg-elev border border-line-soft"
                  alt="Thumbnail"
                />
                <div className="flex-1 min-w-0 flex flex-col gap-3">
                  <div className="min-w-0 grid gap-1">
                    <span className="text-[0.68rem] text-ink-light-soft font-bold uppercase tracking-wider">
                      Track
                    </span>
                    <span className="text-sm font-medium text-ink-light wrap-break-word">
                      {mediaInfo.trackName || "Untitled"}
                    </span>
                  </div>
                  <div className="min-w-0 grid gap-1">
                    <span className="text-[0.68rem] text-ink-light-soft font-bold uppercase tracking-wider">
                      Artist
                    </span>
                    <span className="text-sm font-medium text-ink-light wrap-break-word">
                      {mediaInfo.artistName || "Unknown Artist"}
                    </span>
                  </div>
                </div>
              </div>
              <div className="grid grid-cols-2 gap-3 pt-3 border-t border-line">
                <div className="min-w-0 grid gap-1">
                  <span className="text-[0.68rem] text-ink-light-soft font-bold uppercase tracking-wider">
                    Duration
                  </span>
                  <span className="text-sm font-medium text-ink-light wrap-break-word font-mono">
                    {formatTime(mediaInfo.duration)}
                  </span>
                </div>
                <div className="min-w-0 grid gap-1">
                  <span className="text-[0.68rem] text-ink-light-soft font-bold uppercase tracking-wider">
                    Status
                  </span>
                  <span className="text-sm font-medium text-primary capitalize">
                    {transcribeState}
                  </span>
                </div>
              </div>
            </div>
          </section>

          {mediaInfo && (
            <PublishCard
              publishState={publishMutation.state}
              onPublish={onPublish}
            />
          )}
        </>
      )}
    </article>
  );
}

// frontend/src/components/SourcePanel.svelte
<script lang="ts">
  import type { FetchMediaResponse } from "../lib/api";

  export let activeTab: "source" | "timeline" | "lyrics";
  export let sourceInput = "";
  export let fetchState: "idle" | "loading" | "ready" | "error";
  export let sourceMessage: string;
  export let mediaInfo: FetchMediaResponse | null;
  export let transcribeState: string;
  export let formatTime: (seconds: number) => string;
  export let onFetch: () => void;
  export let onTranscribe: () => void;
</script>

<article class="source-panel" class:hidden-mobile={activeTab !== "source"}>
  <section class="input-section">
    <div class="input-group">
      <span class="label">Source URL</span>
      <div class="input-wrapper">
        <input
          type="url"
          bind:value={sourceInput}
          placeholder="Paste YouTube link here..."
          class:error={fetchState === "error"}
        />
        <div class="input-glow"></div>
      </div>
    </div>

    <div class="action-row">
      <button 
        type="button" 
        class="btn-action primary" 
        disabled={fetchState === "loading"} 
        on:click={onFetch}
      >
        {#if fetchState === "loading"}
          <span class="spinner"></span> Fetching...
        {:else}
          Fetch Media
        {/if}
      </button>
      
      <button
        type="button"
        class="btn-action secondary"
        disabled={!mediaInfo || ["starting", "running", "queued"].includes(transcribeState)}
        on:click={onTranscribe}
      >
        {#if ["starting", "running", "queued"].includes(transcribeState)}
          <span class="pulse"></span> Working...
        {:else}
          Transcribe
        {/if}
      </button>
    </div>

    <div class="status-box" data-state={fetchState}>
      <p>{sourceMessage}</p>
    </div>
  </section>

  {#if mediaInfo}
    <section class="info-card">
      <div class="card-header">
        <span class="tag">Metadata</span>
      </div>
      <div class="info-grid">
        <div class="info-item">
          <span class="info-label">Track</span>
          <span class="info-value">{mediaInfo.trackName || "Untitled"}</span>
        </div>
        <div class="info-item">
          <span class="info-label">Artist</span>
          <span class="info-value">{mediaInfo.artistName || "Unknown Artist"}</span>
        </div>
        <div class="info-row">
          <div class="info-item">
            <span class="info-label">Duration</span>
            <span class="info-value mono">{formatTime(mediaInfo.duration)}</span>
          </div>
          <div class="info-item">
            <span class="info-label">Status</span>
            <span class="info-value status-tag" data-state={transcribeState}>
              {transcribeState}
            </span>
          </div>
        </div>
      </div>
    </section>
  {/if}
</article>

<style>
  .source-panel {
    height: 100%;
    padding: 10px;
    display: flex;
    flex-direction: column;
    gap: 12px;
    overflow-x: hidden;
    overflow-y: auto;
    background: transparent;
  }

  .input-section,
  .info-card {
    border: 1px solid var(--line);
    border-radius: 14px;
    background: rgba(255, 255, 251, 0.88);
    box-shadow: var(--shadow-sm);
  }

  .input-section {
    padding: 18px;
    display: flex;
    flex-direction: column;
    gap: 14px;
  }

  .input-group {
    display: flex;
    flex-direction: column;
    gap: 8px;
  }

  .label {
    font-size: 0.72rem;
    font-weight: 800;
    color: var(--ink-soft);
    text-transform: uppercase;
    letter-spacing: 0.08em;
  }

  .input-wrapper {
    position: relative;
  }

  input {
    width: 100%;
    border: 1px solid #cfd8b7;
    border-radius: 10px;
    background: #fefff5;
    color: var(--ink);
    padding: 0.72rem 0.82rem;
    font-size: 0.88rem;
    outline: none;
    transition: border-color 140ms ease, box-shadow 140ms ease, background 140ms ease;
  }

  input:focus {
    background: #fff;
    border-color: var(--primary-deep);
    box-shadow: 0 0 0 4px rgba(183, 223, 45, 0.18);
  }

  input.error {
    border-color: var(--danger);
  }

  .input-glow {
    display: none;
  }

  .action-row {
    display: grid;
    grid-template-columns: 1fr;
    gap: 8px;
  }

  .btn-action {
    min-height: 42px;
    border-radius: 10px;
    border: 1px solid transparent;
    padding: 0.68rem 0.9rem;
    display: inline-flex;
    align-items: center;
    justify-content: center;
    gap: 0.45rem;
    font-size: 0.84rem;
    font-weight: 800;
    color: var(--ink);
    transition: transform 140ms ease, background 140ms ease, border-color 140ms ease;
  }

  .btn-action:not(:disabled):hover {
    transform: translateY(-1px);
  }

  .btn-action.primary {
    background: linear-gradient(180deg, #d5f45f, var(--primary));
    color: #1e2c06;
    border-color: #a8c92a;
  }

  .btn-action.primary:hover:not(:disabled) {
    background: linear-gradient(180deg, #e0fa73, #c2e849);
  }

  .btn-action.secondary {
    background: #f3f6e7;
    color: #2d371d;
    border-color: var(--line);
  }

  .btn-action.secondary:hover:not(:disabled) {
    background: #edf3d4;
  }

  .btn-action:disabled {
    opacity: 0.58;
    cursor: not-allowed;
  }

  .status-box {
    border-left: 3px solid var(--line);
    border-radius: 10px;
    background: #f7f9ed;
    padding: 0.75rem 0.85rem;
    color: var(--ink-soft);
    font-size: 0.8rem;
    line-height: 1.45;
    word-break: break-word;
  }

  .status-box p {
    margin: 0;
  }

  .status-box[data-state="ready"] {
    border-left-color: #3b7b0d;
    background: #f3fbe9;
    color: #294b13;
  }

  .status-box[data-state="error"] {
    border-left-color: var(--danger);
    background: #fff4f2;
    color: #7a2a2a;
  }

  .info-card {
    padding: 16px;
    display: flex;
    flex-direction: column;
    gap: 14px;
  }

  .card-header {
    display: flex;
    align-items: center;
  }

  .tag {
    display: inline-flex;
    border-radius: 6px;
    background: #eef3df;
    color: #62703e;
    padding: 0.25rem 0.48rem;
    font-size: 0.66rem;
    font-weight: 850;
    text-transform: uppercase;
    letter-spacing: 0.05em;
  }

  .info-grid {
    display: flex;
    flex-direction: column;
    gap: 12px;
  }

  .info-item {
    min-width: 0;
    display: grid;
    gap: 4px;
  }

  .info-label {
    font-size: 0.68rem;
    color: var(--ink-soft);
    font-weight: 750;
  }

  .info-value {
    color: var(--ink);
    font-size: 0.86rem;
    font-weight: 650;
    line-height: 1.4;
    word-break: break-word;
  }

  .info-row {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 12px;
    padding-top: 12px;
    border-top: 1px solid #edf0dd;
  }

  .mono {
    font-family: "IBM Plex Mono", "Consolas", monospace;
    font-size: 0.82rem;
  }

  .status-tag {
    text-transform: capitalize;
    color: var(--primary-deep);
  }

  .spinner {
    width: 14px;
    height: 14px;
    border: 2px solid rgba(31, 44, 6, 0.22);
    border-top-color: #1f2c06;
    border-radius: 50%;
    animation: spin 0.8s linear infinite;
  }

  .pulse {
    width: 8px;
    height: 8px;
    background: var(--primary-deep);
    border-radius: 50%;
    animation: pulse 1s infinite;
  }

  @keyframes spin {
    to {
      transform: rotate(360deg);
    }
  }

  @keyframes pulse {
    50% {
      opacity: 0.42;
    }
  }
</style>
