// frontend/src/App.svelte
<script lang="ts">
  // Syncing props with Svelte 5 TimelinePanel
  import { onDestroy, onMount } from "svelte";

  import {
    fetchMedia,
    fetchPeaks,
    getAudioUrl,
    publishLyrics,
    requestPublishChallenge,
    requestTranscription,
    streamTranscription,
    type FetchMediaResponse,
    type PeaksResponse,
  } from "./lib/api";
  import {
    createDebouncedDraftAutosave,
    createDraftManager,
  } from "./lib/app/draftManager";
  import { createEditorLifecycleController } from "./lib/app/editorLifecycleController";
  import { formatTime } from "./lib/app/formatters";
  import { createGlobalKeydownHandler } from "./lib/app/keyboardShortcuts";
  import { createLyricsActions } from "./lib/app/lyricsActions";
  import { buildPublishPayload } from "./lib/app/publishPayload";
  import {
    createPublishFlowMachine,
    type PublishFlowState,
  } from "./lib/app/publishFlow";
  import { solvePowInWorker } from "./lib/app/powWorkerClient";
  import {
    fetchMediaForEditor,
    runTranscriptionFlow,
  } from "./lib/app/mediaWorkflow";
  import { findActiveLyricIndex, type LyricLine } from "./lib/lyricsTimeline";
  import LyricsPanel from "./components/LyricsPanel.svelte";
  import MobileTabs from "./components/MobileTabs.svelte";
  import SourcePanel from "./components/SourcePanel.svelte";
  import TimelinePanel from "./components/TimelinePanel.svelte";
  import VideoPlayer from "./components/VideoPlayer.svelte";
  import {
    LyricsStore,
    type LyricsState,
  } from "./lib/LyricsStore";
  import { MediaController } from "./lib/MediaController";
  import { WaveformController } from "./lib/WaveformController";

  type TabId = "source" | "timeline" | "lyrics";

  const tabs: { id: TabId; label: string }[] = [
    { id: "source", label: "Source" },
    { id: "timeline", label: "Timeline" },
    { id: "lyrics", label: "Lyrics" },
  ];

  const mediaController = new MediaController();
  const waveformController = new WaveformController();
  const lyricsStore = new LyricsStore();
  const draftManager = createDraftManager();
  const draftAutosave = createDebouncedDraftAutosave({
    save: (videoId, payload) => draftManager.save(videoId, payload),
    delayMs: 1000,
  });

  let activeTab: TabId = "timeline";
  let sourceInput = "";
  let fetchState: "idle" | "loading" | "ready" | "error" = "idle";
  let sourceMessage = "No source loaded yet.";
  let transcribeState = "idle";
  let mediaInfo: FetchMediaResponse | null = null;
  let peaksInfo: PeaksResponse | null = null;
  let peaksState: "idle" | "loading" | "ready" | "error" = "idle";
  let peaksMessage = "No peaks generated yet.";
  let peakPreview: number[] = [];
  let lyricsState: LyricsState = lyricsStore.getState();
  let waveformHost: HTMLDivElement | null = null;
  let waveformTimelineHost: HTMLDivElement | null = null;
  let zoomLevel = 52;
  let loopEnabled = false;

  let waveScrollLeft = 0;
  let wavePxPerSec = zoomLevel;

  let dragBaseState: any = null;
  let isPlaying = false;
  let currentTime = 0;
  let duration = 0;
  let transcribeAbortController: AbortController | null = null;
  let publishState: PublishFlowState;
  let lastAutosaveFingerprint = "";

  const lyricsActions = createLyricsActions({
    lyricsStore,
    mediaController,
    getCurrentTime: () => currentTime,
  });

  const lifecycleController = createEditorLifecycleController({
    mediaController,
    waveformController,
    lyricsStore,
    getSyncedLines: () => lyricsState.doc.syncedLines,
    onLyricsStateChange: (next) => {
      lyricsState = next;
    },
    onCurrentTimeChange: (value) => {
      currentTime = value;
    },
    onDurationChange: (value) => {
      duration = value;
    },
    onPlayStateChange: (value) => {
      isPlaying = value;
    },
    onError: (message) => {
      sourceMessage = message;
      fetchState = "error";
    },
  });

  const publishFlow = createPublishFlowMachine((next) => {
    publishState = next;
  });
  publishState = publishFlow.getState();

  function saveDraft() {
    if (!mediaInfo) {
      sourceMessage = "Load media before saving a draft.";
      return;
    }

    draftManager.save(mediaInfo.videoId, {
      doc: lyricsState.doc,
      selectedLineId: lyricsState.selectedLineId,
    });
    sourceMessage = "Draft saved locally.";
  }

  function maybeRestoreDraft(videoId: string) {
    const draft = draftManager.load(videoId);
    if (!draft) {
      return;
    }

    const shouldRestore = confirm(
      "Found a local draft for this video. Do you want to restore it?",
    );

    if (!shouldRestore) {
      return;
    }

    lyricsStore.loadDraft(draft.doc, draft.selectedLineId ?? null);
    sourceMessage = "Draft restored from local storage.";
  }

  async function handlePublish() {
    if (!mediaInfo) {
      sourceMessage = "Load media before publishing.";
      return;
    }

    await publishFlow.run({
      buildPayload: () =>
        buildPublishPayload({
          lyricsState,
          mediaInfo,
          exportLrc: () => lyricsStore.exportToLrc(),
        }),
      requestChallenge: requestPublishChallenge,
      solvePow: ({ prefix, targetHex, onProgress }) =>
        solvePowInWorker({
          prefix,
          targetHex,
          onProgress,
        }),
      publish: ({ payload, publishToken }) =>
        publishLyrics({
          payload,
          publishToken,
        }),
    });
  }

  let videoPlayerRef: VideoPlayer;
  let isSidebarCollapsed = false;

  function handleTimeUpdate(time: number) {
    currentTime = time;
    waveformController.syncTime(time);

    // Auto-follow lyrics during playback
    const lines = lyricsState.doc.syncedLines;
    const activeIndex = findActiveLyricIndex(lines, time);
    if (activeIndex >= 0) {
      const activeLineId = lines[activeIndex].id;
      lyricsStore.setActiveLine(activeLineId);
    } else {
      lyricsStore.setActiveLine(null);
    }
  }

  function handlePlayStateChange(playing: boolean) {
    isPlaying = playing;
  }

  function handleDurationChange(dur: number) {
    duration = dur;
  }

  const onGlobalKeydown = createGlobalKeydownHandler({
    onSaveDraft: saveDraft,
    onUndo: lyricsActions.undo,
    onRedo: lyricsActions.redo,
    onTapSync: lyricsActions.tapSync,
    onTogglePlayback: () =>
      isPlaying ? videoPlayerRef?.pause() : videoPlayerRef?.play(),
    onSelectOffset: (offset) => lyricsStore.selectByOffset(offset),
    onFineSeek: (delta) => videoPlayerRef?.seekBy(delta),
  });

  onMount(() => {
    lifecycleController.mount({
      waveformHost,
      waveformTimelineHost,
      zoomLevel,
      onGlobalKeydown,
      onWaveScroll: (px) => { waveScrollLeft = px; },
      onWaveZoom: (px) => { wavePxPerSec = px; },
    });
  });

  onDestroy(() => {
    draftAutosave.flushNow();
    lifecycleController.dispose();
    transcribeAbortController?.abort();
  });

  $: if (mediaInfo?.videoId) {
    const fingerprint = JSON.stringify({
      videoId: mediaInfo.videoId,
      doc: lyricsState.doc,
      selectedLineId: lyricsState.selectedLineId,
    });

    if (fingerprint !== lastAutosaveFingerprint) {
      lastAutosaveFingerprint = fingerprint;
      draftAutosave.schedule(mediaInfo.videoId, {
        doc: lyricsState.doc,
        selectedLineId: lyricsState.selectedLineId,
      });
    }
  }

  $: if (lifecycleController.isLoopSelectionOutdated(lyricsState.selectedLineId)) {
    loopEnabled = false;
  }
  $: lifecycleController.syncRegions(
    lyricsState.doc.syncedLines,
    lyricsState.activeLineId ?? lyricsState.selectedLineId,
  );

  async function handleFetch() {
    if (!sourceInput.trim()) {
      sourceMessage = "Please enter a valid source URL.";
      fetchState = "error";
      return;
    }

    try {
      fetchState = "loading";
      sourceMessage = "Fetching metadata and caching audio...";
      transcribeState = "idle";
      peaksInfo = null;
      peaksState = "loading";
      peaksMessage = "Generating waveform peaks...";

      const result = await fetchMediaForEditor({
        sourceUrl: sourceInput.trim(),
        fetchMediaFn: fetchMedia,
        fetchPeaksFn: fetchPeaks,
        getAudioUrlFn: getAudioUrl,
        mediaController,
        waveformController,
        lyricsStore,
        restoreDraft: maybeRestoreDraft,
      });

      mediaInfo = result.mediaInfo;
      peaksInfo = result.peaks.peaksInfo;
      peaksState = result.peaks.peaksState;
      peaksMessage = result.peaks.peaksMessage;
      sourceMessage = result.sourceMessage;
      fetchState = "ready";
      loopEnabled = false;
      publishFlow.reset();
      lastAutosaveFingerprint = "";
    } catch (error) {
      peaksState = "error";
      peaksMessage = "Failed to load waveform peaks.";
      fetchState = "error";
      sourceMessage = error instanceof Error ? error.message : "Failed to fetch source.";
    }
  }

  function handleZoomChange(event: Event) {
    const nextZoom = Number((event.currentTarget as HTMLInputElement).value);
    zoomLevel = nextZoom;
    wavePxPerSec = nextZoom;
    waveformController.setZoom(nextZoom);
  }

  function toggleLoopForActiveLine() {
    if (!lyricsState.selectedLineId) {
      return;
    }

    loopEnabled = waveformController.toggleLoop(lyricsState.selectedLineId, lyricsState.doc.syncedLines);
  }

  async function handleTranscribe() {
    if (!mediaInfo) return;
    
    transcribeAbortController = new AbortController();
    try {
      transcribeState = "starting";
      const result = await runTranscriptionFlow({
        mediaInfo,
        requestFn: requestTranscription,
        streamFn: streamTranscription,
        lyricsStore,
        onStatus: (status) => {
          transcribeState = status;
        },
        signal: transcribeAbortController.signal
      });
      transcribeState = result.transcribeState;
      sourceMessage = result.sourceMessage;
    } catch (e) {
      transcribeState = "error";
      sourceMessage = "Transcription failed.";
    }
  }
</script>

<main class="app-shell">
  <header class="top-header">
    <div class="logo">
      <div class="logo-icon"></div>
      <h1>Lyrics Studio</h1>
    </div>
    <div class="header-actions">
      <button class="btn ghost compact" on:click={lyricsActions.undo} disabled={!lyricsState.canUndo}>Undo</button>
      <button class="btn ghost compact" on:click={lyricsActions.redo} disabled={!lyricsState.canRedo}>Redo</button>
      <button class="btn primary compact" on:click={saveDraft}>Save Draft</button>
    </div>
  </header>

  <div class="app-body">
    <div class="workspace-top">
      <div class="sidebar-wrapper" style="width: {isSidebarCollapsed ? '40px' : '320px'}">
        <aside class="sidebar-content" class:collapsed={isSidebarCollapsed}>
          <SourcePanel
            {activeTab}
            bind:sourceInput
            {fetchState}
            {sourceMessage}
            {mediaInfo}
            {publishState}
            {transcribeState}
            {formatTime}
            onFetch={handleFetch}
            onPublish={handlePublish}
            onTranscribe={handleTranscribe}
          />
        </aside>
        <button class="sidebar-toggle" on:click={() => isSidebarCollapsed = !isSidebarCollapsed}>
          {isSidebarCollapsed ? '→' : '←'}
        </button>
      </div>

      <section class="main-stage">
        <VideoPlayer
          videoId={mediaInfo?.videoId ?? null}
          onTimeUpdate={handleTimeUpdate}
          onPlayStateChange={handlePlayStateChange}
          onDurationChange={handleDurationChange}
          bind:this={videoPlayerRef}
        />
      </section>

      <aside class="right-panel">
        <LyricsPanel
          {activeTab}
          {lyricsState}
          {formatTime}
          onSetTab={lyricsActions.setTab}
          onSeekLine={lyricsActions.seekLine}
          onEditLineText={lyricsActions.editLineText}
          onSelectLine={lyricsActions.selectLine}
          onReorder={lyricsActions.reorder}
          onInsertAfter={lyricsActions.insertAfter}
          onSplit={lyricsActions.split}
          onMerge={lyricsActions.merge}
          onDelete={lyricsActions.delete}
          onNudge={lyricsActions.nudgeLine}
          onSetPlainLyrics={lyricsActions.setPlainLyrics}
          onUpdateMetaField={lyricsActions.updateMetaField}
          onImportLrc={lyricsActions.importLrc}
          onExportLrc={lyricsActions.exportLrc}
        />
      </aside>
    </div>

    <div class="workspace-bottom">
      <TimelinePanel
        activeTab="timeline"
        {mediaInfo}
        {currentTime}
        {duration}
        {peaksState}
        {peaksMessage}
        {zoomLevel}
        {loopEnabled}
        {lyricsState}
        {waveScrollLeft}
        {wavePxPerSec}
        canUndo={lyricsState.canUndo}
        canRedo={lyricsState.canRedo}
        hasSelectedLine={Boolean(lyricsState.selectedLineId)}
        {formatTime}
        onUndo={lyricsActions.undo}
        onRedo={lyricsActions.redo}
        onSaveDraft={saveDraft}
        onZoomChange={handleZoomChange}
        onToggleLoop={toggleLoopForActiveLine}
        onSelectLine={lyricsActions.selectLine}
        onRegionResize={lyricsActions.resizeLineLive}
        onRegionResizeCommit={(id, s, e) => {
          lyricsActions.resizeLineCommit(id, s, e, dragBaseState);
          dragBaseState = null;
        }}
        onRegionResizeStart={() => {
          dragBaseState = lyricsStore.getHistoryState();
        }}
        onSeekBy={(delta) => videoPlayerRef?.seekBy(delta)}
        onSeekTo={(time) => videoPlayerRef?.seekTo(time)}
        onTogglePlayback={() => isPlaying ? videoPlayerRef?.pause() : videoPlayerRef?.play()}
        bind:waveformHost
        bind:waveformTimelineHost
      />
    </div>
  </div>
</main>


<style>
  :global(body, html) {
    margin: 0;
    padding: 0;
    height: 100%;
  }

  .app-shell {
    height: 100vh;
    width: 100vw;
    display: flex;
    flex-direction: column;
    overflow: hidden;
    background: transparent;
  }

  .top-header {
    height: 56px;
    padding: 0 1.25rem;
    flex-shrink: 0;
    display: flex;
    align-items: center;
    justify-content: space-between;
    background: rgba(255, 255, 251, 0.86);
    border-bottom: 1px solid var(--line);
    backdrop-filter: blur(14px);
  }

  .logo {
    display: flex;
    align-items: center;
    gap: 0.75rem;
  }

  .logo-icon {
    width: 18px;
    height: 18px;
    border-radius: 6px;
    background: linear-gradient(135deg, var(--primary), #e4f766);
    box-shadow: inset 0 -2px 0 rgba(0, 0, 0, 0.08);
  }

  .logo h1 {
    margin: 0;
    font-size: 1.04rem;
    font-weight: 800;
    letter-spacing: -0.03em;
    color: var(--ink);
  }

  .header-actions {
    display: flex;
    align-items: center;
    gap: 0.5rem;
  }

  .app-body {
    min-height: 0;
    flex: 1;
    display: flex;
    flex-direction: column;
  }

  .workspace-top {
    min-height: 0;
    flex: 1;
    display: grid;
    grid-template-columns: auto minmax(460px, 1fr) 400px;
    gap: 8px;
    padding: 8px;
  }

  .workspace-bottom {
    height: 302px;
    flex-shrink: 0;
    padding: 0 8px 8px;
  }

  .sidebar-wrapper {
    width: 320px;
    min-width: 40px;
    height: 100%;
    display: flex;
    flex-direction: row-reverse;
    overflow: hidden;
    border: 1px solid var(--line);
    border-radius: var(--radius-lg);
    background: rgba(255, 255, 251, 0.7);
    box-shadow: var(--shadow-sm);
    transition: width 220ms ease;
  }

  .sidebar-content {
    min-width: 0;
    flex: 1;
    overflow-y: auto;
    opacity: 1;
    transition: opacity 160ms ease;
  }

  .sidebar-content.collapsed {
    opacity: 0;
    pointer-events: none;
  }

  .sidebar-toggle {
    width: 34px;
    flex-shrink: 0;
    border: 0;
    border-right: 1px solid var(--line);
    background: #f3f6e5;
    color: var(--ink-soft);
    font-size: 0.9rem;
  }

  .sidebar-toggle:hover {
    background: #ebf1d2;
    color: var(--ink);
  }

  .main-stage {
    min-width: 0;
    min-height: 0;
    display: flex;
    align-items: center;
    justify-content: center;
    padding: 14px;
    border: 1px solid var(--line);
    border-radius: var(--radius-lg);
    background: linear-gradient(180deg, rgba(14, 15, 20, 0.96), rgba(0, 0, 0, 0.98)), #000;
    box-shadow: var(--shadow);
    overflow: hidden;
  }

  .right-panel {
    min-width: 0;
    height: 100%;
    overflow: hidden;
    border: 1px solid var(--line);
    border-radius: var(--radius-lg);
    background: rgba(255, 255, 251, 0.82);
    box-shadow: var(--shadow-sm);
  }

  @media (max-width: 1180px) {
    .workspace-top {
      grid-template-columns: auto minmax(360px, 1fr);
    }

    .right-panel {
      display: none;
    }
  }

  @media (max-width: 760px) {
    .app-shell {
      height: auto;
      min-height: 100vh;
      overflow: visible;
    }

    .top-header {
      position: sticky;
      top: 0;
      z-index: 10;
    }

    .workspace-top {
      grid-template-columns: 1fr;
      grid-auto-rows: auto;
    }

    .sidebar-wrapper {
      display: none;
    }

    .main-stage {
      min-height: auto;
    }

    .workspace-bottom {
      height: 360px;
    }
  }
</style>

// lyrike-studio/app/page.tsx
"use client";

import { useState, useRef, useCallback, useEffect } from "react";
import dynamic from "next/dynamic";
import {
  LyricsProvider,
  useLyrics,
} from "@/features/editor/context/LyricsContext";
import { SourcePanel } from "@/features/editor/components/SourcePanel";
import { TimelinePanel } from "@/features/editor/components/TimelinePanel";
import { LyricsPanel } from "@/features/editor/components/LyricsPanel";
import { VideoPlayer } from "@/features/editor/components/VideoPlayer";
import { MobileTabs } from "@/shared/ui/MobileTabs";
import {
  fetchMedia,
  fetchPeaks,
  getAudioUrl,
  publishLyrics,
  requestPublishChallenge,
  requestTranscription,
  streamTranscription,
  type FetchMediaResponse,
  type PeaksResponse,
} from "@/lib/api";
import { createDraftManager } from "@/lib/app/draftManager";
import { formatTime } from "@/lib/app/formatters";
import { buildPublishPayload } from "@/lib/app/publishPayload";
import {
  createPublishFlowMachine,
  type PublishFlowState,
} from "@/lib/app/publishFlow";
import { solvePowInWorker } from "@/lib/app/powWorkerClient";
import {
  fetchMediaForEditor,
  runTranscriptionFlow,
} from "@/lib/app/mediaWorkflow";
import { findActiveLyricIndex } from "@/lib/lyricsTimeline";
import type { LyricLine } from "@/lib/lyricsTimeline";
import { MediaController } from "@/lib/MediaController";
import { WaveformController } from "@/lib/WaveformController";
import { useMemo } from "react";

type TabId = "source" | "timeline" | "lyrics";

const TABS: { id: TabId; label: string }[] = [
  { id: "source", label: "Source" },
  { id: "timeline", label: "Timeline" },
  { id: "lyrics", label: "Lyrics" },
];

const draftManager = createDraftManager();

function EditorImpl() {
  const {
    state,
    store,
    setTab,
    setActiveLine,
    selectLine,
    editText,
    selectByOffset,
    hydrateFromMedia,
    loadDraft,
    setLineRangeLive,
    setLineRangeCommit,
    tapSync,
    insertAfter,
    deleteLine,
    reorder,
    splitLine,
    mergeWithPrevious,
    nudgeLine,
    setPlainLyrics,
    setMeta,
    importFromLrc,
    exportToLrc,
    undo,
    redo,
    getHistoryState,
  } = useLyrics();

  const mediaController = useMemo(() => new MediaController(), []);
  const waveformController = useMemo(() => new WaveformController(), []);
  const videoPlayerRef = useRef<any>(null);

  const [activeTab, setActiveTab] = useState<TabId>("timeline");
  const [sourceInput, setSourceInput] = useState("");
  const [fetchState, setFetchState] = useState<
    "idle" | "loading" | "ready" | "error"
  >("idle");
  const [sourceMessage, setSourceMessage] = useState("No source loaded yet.");
  const [transcribeState, setTranscribeState] = useState("idle");
  const [mediaInfo, setMediaInfo] = useState<FetchMediaResponse | null>(null);
  const [peaksInfo, setPeaksInfo] = useState<PeaksResponse | null>(null);
  const [peaksState, setPeaksState] = useState<
    "idle" | "loading" | "ready" | "error"
  >("idle");
  const [peaksMessage, setPeaksMessage] = useState("No peaks generated yet.");

  const [zoomLevel, setZoomLevel] = useState(52);
  const [loopEnabled, setLoopEnabled] = useState(false);
  const [waveScrollLeft, setWaveScrollLeft] = useState(0);
  const [wavePxPerSec, setWavePxPerSec] = useState(52);

  const [dragBaseState, setDragBaseState] = useState<any>(null);
  const [isPlaying, setIsPlaying] = useState(false);
  const [currentTime, setCurrentTime] = useState(0);
  const [duration, setDuration] = useState(0);
  const [transcribeAbortController, setTranscribeAbortController] =
    useState<AbortController | null>(null);
  const [publishState, setPublishState] = useState<PublishFlowState | null>(
    null,
  );

  const [isSidebarCollapsed, setIsSidebarCollapsed] = useState(false);

  const publishFlow = createPublishFlowMachine((next) => setPublishState(next));
  useEffect(() => setPublishState(publishFlow?.getState() ?? null), []);

  const handleTimeUpdate = useCallback(
    (time: number) => {
      setCurrentTime(time);
      const lines = state.doc.syncedLines;
      const activeIndex = findActiveLyricIndex(lines, time);
      if (activeIndex >= 0) {
        setActiveLine(lines[activeIndex].id);
      } else {
        setActiveLine(null);
      }
    },
    [state.doc.syncedLines, setActiveLine],
  );

  const handlePlayStateChange = useCallback((playing: boolean) => {
    setIsPlaying(playing);
  }, []);

  const handleDurationChange = useCallback((dur: number) => {
    setDuration(dur);
  }, []);

  const handleZoomChange = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => {
      const nextZoom = Number(e.target.value);
      setZoomLevel(nextZoom);
      setWavePxPerSec(nextZoom);
    },
    [],
  );

  const handleToggleLoop = useCallback(() => {
    if (!state.selectedLineId) return;
    setLoopEnabled(!loopEnabled);
  }, [state.selectedLineId, loopEnabled]);

  const maybeRestoreDraft = useCallback(
    (videoId: string) => {
      const draft = draftManager.load(videoId);
      if (!draft) return;
      const shouldRestore = confirm(
        "Found a local draft for this video. Do you want to restore it?",
      );
      if (!shouldRestore) return;
      loadDraft(draft.doc, draft.selectedLineId ?? null);
      setSourceMessage("Draft restored from local storage.");
    },
    [loadDraft],
  );

  const saveDraft = useCallback(() => {
    if (!mediaInfo) {
      setSourceMessage("Load media before saving a draft.");
      return;
    }
    draftManager.save(mediaInfo.videoId, {
      doc: state.doc,
      selectedLineId: state.selectedLineId,
    });
    setSourceMessage("Draft saved locally.");
  }, [mediaInfo, state]);

  const handlePublish = useCallback(async () => {
    if (!mediaInfo) {
      setSourceMessage("Load media before publishing.");
      return;
    }
    await publishFlow.run({
      buildPayload: () =>
        buildPublishPayload({
          lyricsState: state,
          mediaInfo,
          exportLrc: () => exportToLrc(),
        }),
      requestChallenge: requestPublishChallenge,
      solvePow: ({ prefix, targetHex, onProgress }) =>
        solvePowInWorker({ prefix, targetHex, onProgress }),
      publish: ({ payload, publishToken }) =>
        publishLyrics({ payload, publishToken }),
    });
  }, [mediaInfo, state]);

  const handleFetch = useCallback(async () => {
    if (!sourceInput.trim()) {
      setSourceMessage("Please enter a valid source URL.");
      setFetchState("error");
      return;
    }
    try {
      setFetchState("loading");
      setSourceMessage("Fetching metadata and caching audio...");
      setTranscribeState("idle");
      setPeaksInfo(null);
      setPeaksState("loading");
      setPeaksMessage("Generating waveform peaks...");

      const result = await fetchMediaForEditor({
        sourceUrl: sourceInput.trim(),
        fetchMediaFn: fetchMedia,
        fetchPeaksFn: fetchPeaks,
        getAudioUrlFn: getAudioUrl,
        restoreDraft: maybeRestoreDraft,
        mediaController,
        waveformController,
        onHydrateFromMedia: hydrateFromMedia,
      });

      setMediaInfo(result.mediaInfo);
      setPeaksInfo(result.peaks.peaksInfo);
      setPeaksState(result.peaks.peaksState);
      setPeaksMessage(result.peaks.peaksMessage);
      setSourceMessage(result.sourceMessage);
      setFetchState("ready");
      setLoopEnabled(false);
      publishFlow.reset();
    } catch (error) {
      setPeaksState("error");
      setPeaksMessage("Failed to load waveform peaks.");
      setFetchState("error");
      setSourceMessage(
        error instanceof Error ? error.message : "Failed to fetch source.",
      );
    }
  }, [sourceInput, maybeRestoreDraft, mediaController, waveformController, hydrateFromMedia]);

  const handleTranscribe = useCallback(async () => {
    if (!mediaInfo) return;
    const abortController = new AbortController();
    setTranscribeAbortController(abortController);
    try {
      setTranscribeState("starting");
      const result = await runTranscriptionFlow({
        mediaInfo,
        requestFn: requestTranscription,
        streamFn: streamTranscription,
        onImportLrc: importFromLrc,
        onStatus: (status) => setTranscribeState(status),
        signal: abortController.signal,
      });
      setTranscribeState(result.transcribeState);
      setSourceMessage(result.sourceMessage);
    } catch (e) {
      setTranscribeState("error");
      setSourceMessage("Transcription failed.");
    }
  }, [mediaInfo, store]);

  const handleZoomChangePx = useCallback((px: number) => {
    setZoomLevel(px);
    setWavePxPerSec(px);
  }, []);

  const handleScroll = useCallback((px: number) => {
    setWaveScrollLeft(px);
  }, []);

  const handleSeekTo = useCallback((time: number) => {
    videoPlayerRef.current?.seekTo(time);
  }, []);

  const formatTimeFn = useCallback(
    (seconds: number) => formatTime(seconds),
    [],
  );

  return (
    <main className="app-shell">
      <header className="top-header">
        <div className="logo">
          <div className="logo-icon" />
          <h1>Lyrics Studio</h1>
        </div>
        <div className="header-actions">
          <button
            className="btn ghost compact"
            onClick={undo}
            disabled={!state.canUndo}
          >
            Undo
          </button>
          <button
            className="btn ghost compact"
            onClick={redo}
            disabled={!state.canRedo}
          >
            Redo
          </button>
          <button className="btn primary compact" onClick={saveDraft}>
            Save Draft
          </button>
        </div>
      </header>

      <div className="app-body">
        <div className="workspace-top">
          <div
            className="sidebar-wrapper"
            style={{ width: isSidebarCollapsed ? "40px" : "320px" }}
          >
            <aside
              className={`sidebar-content ${isSidebarCollapsed ? "collapsed" : ""}`}
            >
              <SourcePanel
                activeTab={activeTab}
                sourceInput={sourceInput}
                setSourceInput={setSourceInput}
                fetchState={fetchState}
                sourceMessage={sourceMessage}
                mediaInfo={mediaInfo}
                publishState={publishState!}
                transcribeState={transcribeState}
                formatTime={formatTimeFn}
                onFetch={handleFetch}
                onPublish={handlePublish}
                onTranscribe={handleTranscribe}
              />
            </aside>
            <button
              className="sidebar-toggle"
              onClick={() => setIsSidebarCollapsed(!isSidebarCollapsed)}
            >
              {isSidebarCollapsed ? "→" : "←"}
            </button>
          </div>

          <section className="main-stage">
            <VideoPlayer
              ref={videoPlayerRef}
              videoId={mediaInfo?.videoId ?? null}
              onTimeUpdate={handleTimeUpdate}
              onPlayStateChange={handlePlayStateChange}
              onDurationChange={handleDurationChange}
            />
          </section>

          <aside className="right-panel">
            <LyricsPanel
              activeTab={activeTab}
              lyricsState={state}
              formatTime={formatTimeFn}
              onSetTab={setTab}
              onSeekLine={(line) => videoPlayerRef.current?.seekTo(line.start)}
              onEditLineText={editText}
              onSelectLine={selectLine}
              onReorder={reorder}
              onInsertAfter={insertAfter}
              onSplit={splitLine}
              onMerge={mergeWithPrevious}
              onDelete={deleteLine}
              onNudge={(line, edge, delta) => nudgeLine(line.id, edge, delta)}
              onSetPlainLyrics={setPlainLyrics}
              onUpdateMetaField={(key, value) =>
                setMeta({ [key]: key === 'offset' ? Number(value) : value } as any)
              }
              onImportLrc={importFromLrc}
              onExportLrc={exportToLrc}
            />
          </aside>
        </div>

        <div className="workspace-bottom">
          <TimelinePanel
            activeTab="timeline"
            mediaInfo={mediaInfo}
            lyricsState={state}
            isPlaying={isPlaying}
            currentTime={currentTime}
            duration={duration}
            peaksState={peaksState}
            peaksMessage={peaksMessage}
            zoomLevel={zoomLevel}
            loopEnabled={loopEnabled}
            canUndo={state.canUndo}
            canRedo={state.canRedo}
            hasSelectedLine={Boolean(state.selectedLineId)}
            waveScrollLeft={waveScrollLeft}
            wavePxPerSec={wavePxPerSec}
            formatTime={formatTimeFn}
            onUndo={undo}
            onRedo={redo}
            onSaveDraft={saveDraft}
            onZoomChange={handleZoomChangePx}
            onToggleLoop={handleToggleLoop}
            onSelectLine={selectLine}
            onRegionResize={setLineRangeLive}
            onRegionResizeCommit={(id, s, e) => {
              setLineRangeCommit(id, s, e, dragBaseState);
              setDragBaseState(null);
            }}
            onRegionResizeStart={() => setDragBaseState(getHistoryState())}
            onScroll={handleScroll}
            onSeekBy={(delta) => videoPlayerRef.current?.seekBy(delta)}
            onSeekTo={handleSeekTo}
            onTogglePlayback={() =>
              isPlaying
                ? videoPlayerRef.current?.pause()
                : videoPlayerRef.current?.play()
            }
            waveformController={waveformController}
            mediaController={mediaController}
            peaksInfo={peaksInfo}
            audioUrl={mediaInfo?.audioUrl ? getAudioUrl(mediaInfo.audioUrl) : null}
          />
        </div>
      </div>
    </main>
  );
}

const Editor = dynamic(() => Promise.resolve(EditorImpl), { ssr: false });

export default function Home() {
  return (
    <LyricsProvider>
      <Editor />
    </LyricsProvider>
  );
}
